Repository DataDog/pupernetes, pull requests merged in 2018-07, with the labels that each got.

#79 Fix the abspath of pupernetes, propagate SUDO_USER to the unit env
  pkg/job/systemd.go
Labels: bug

#80 Introduce release notes
  RELEASE.md
  releasenotes.md
Labels: enhancement

#84 Fix the re-apply system
  .circleci/config.yml
  pkg/run/readiness.go
  pkg/run/run.go
Labels: bug

#71 Refactor CI, introduce examples
  .ci/pupernetes-validation.sh
  .ci/pupernetes-validation.yaml
  .circleci/config.yml
  .travis.yml
  README.md
  examples/circleci.yaml
  examples/travis.yaml
Labels: other

#89 Logging improvements on setup requirements
  cmd/main.go
  pkg/setup/requirements/requirements.go
Labels: enhancement

#91 Introduce a timeout and a sig handler during downloads
  cmd/cli/cmd.go
  docs/pupernetes_daemon.md
  docs/pupernetes_daemon_clean.md
  docs/pupernetes_daemon_run.md
  docs/pupernetes_daemon_setup.md
  pkg/config/config.go
  pkg/setup/binary.go
  pkg/setup/setup.go
Labels: enhancement

#92 Improve circleci
  .circleci/config.yml
  .travis.yml
  Makefile
  RELEASE.md
  scripts/update/license.sh
Labels: other, refactoring

#93 Use kube proxy configuration file
  pkg/setup/templates/1.10.go
  pkg/setup/templates/1.11.go
Labels: enhancement

#96 Do create the directory for pod logs
  pkg/setup/setup.go
Labels: bug

#97 Fix a typo in the dig command
  README.md
Labels: other

#99 Introduce the audit logs to dir
  docs/pupernetes_daemon.md
  docs/pupernetes_daemon_clean.md
  docs/pupernetes_daemon_run.md
  docs/pupernetes_daemon_setup.md
  pkg/config/config.go
  pkg/options/clean.go
  pkg/options/clean_test.go
  pkg/setup/clean.go
  pkg/setup/setup.go
  pkg/setup/templates/1.10.go
  pkg/setup/templates/1.11.go
  pkg/setup/templates/1.5.go
  pkg/setup/templates/1.6.go
  pkg/setup/templates/1.7.go
  pkg/setup/templates/1.8.go
  pkg/setup/templates/1.9.go
Labels: enhancement

#98 API aggregation, remove intermediate CA
  pkg/setup/secrets.go
  pkg/setup/templates/1.10.go
  pkg/setup/templates/1.11.go
  pkg/setup/templates/1.5.go
  pkg/setup/templates/1.6.go
  pkg/setup/templates/1.7.go
  pkg/setup/templates/1.8.go
  pkg/setup/templates/1.9.go
Labels: enhancement

#100 Introduce skip probe
  cmd/cli/cmd.go
  docs/pupernetes_daemon_run.md
  pkg/config/config.go
  pkg/run/readiness.go
  pkg/run/run.go
  pkg/run/stop.go
Labels: enhancement

#101 Fix typo
  pkg/run/state/state.go
Labels: bug

#103 travis: fix when cache is missing
  .travis.yml
Labels: bug
