Repository DataDog/pupernetes, pull requests merged in 2018-08, with the labels that each got.

#106 Remove useless stage in audit logs
  pkg/setup/templates/1.10.go
  pkg/setup/templates/1.11.go
  pkg/setup/templates/1.8.go
  pkg/setup/templates/1.9.go
Labels: enhancement

#110 Extend the audit logs to everything
  pkg/setup/templates/1.10.go
  pkg/setup/templates/1.11.go
  pkg/setup/templates/1.8.go
  pkg/setup/templates/1.9.go
Labels: enhancement

#108 Introduce the keep verb
  .circleci/config.yml
  cmd/cli/cmd.go
  docs/pupernetes_daemon.md
  docs/pupernetes_daemon_clean.md
  docs/pupernetes_daemon_run.md
  docs/pupernetes_daemon_setup.md
  pkg/config/config.go
  pkg/options/clean.go
  pkg/options/clean_test.go
  pkg/options/drain.go
  pkg/options/options.go
  pkg/setup/setup.go
Labels: enhancement

#107 Create Kubernetes 1.12 template collection
  .travis.yml
  README.md
  pkg/setup/templates/1.12.go
  pkg/setup/templates/manifests.go
Labels: enhancement

#111 Refactor options package to use sets.
  cmd/cli/cmd.go
  docs/pupernetes_daemon_run.md
  pkg/options/clean.go
  pkg/options/clean_test.go
  pkg/options/drain.go
  pkg/options/drain_test.go
  pkg/options/options.go
  pkg/options/options_test.go
Labels: refactoring

#114 examples: upgrade to the latest pupernetes
  RELEASE.md
  examples/circleci.yaml
  examples/travis.yaml
Labels: other

#115 containerd: kill move to process
  pkg/setup/templates/1.10.go
  pkg/setup/templates/1.11.go
  pkg/setup/templates/1.12.go
  pkg/setup/templates/1.9.go
Labels: bug

#117 resolv: remove the extension .conf
  pkg/setup/getter.go
  pkg/setup/templates/1.10.go
  pkg/setup/templates/1.11.go
  pkg/setup/templates/1.12.go
  pkg/setup/templates/1.5.go
  pkg/setup/templates/1.6.go
  pkg/setup/templates/1.7.go
  pkg/setup/templates/1.8.go
  pkg/setup/templates/1.9.go
Labels: bug

#116 versions: upgrade hyperkube, etcd and containerd
  docs/pupernetes_daemon.md
  docs/pupernetes_daemon_clean.md
  docs/pupernetes_daemon_run.md
  docs/pupernetes_daemon_setup.md
  pkg/config/config.go
  pkg/setup/setup.go
Labels: enhancement
