Repository DataDog/pupernetes, pull requests merged in 2018-06, with the labels that each got.

#41 Introduce the daemon and the reset commands
  .circleci/config.yml
  cmd/cli/cmd.go
  docs/pupernetes.md
  docs/pupernetes_daemon.md
  docs/pupernetes_daemon_clean.md
  docs/pupernetes_daemon_run.md
  docs/pupernetes_daemon_setup.md
  docs/pupernetes_reset.md
  pkg/api/api.go
  pkg/api/client.go
  pkg/config/config.go
  pkg/run/delete.go
  pkg/run/run.go
  pkg/run/stop.go
  pkg/setup/binary.go
Labels: enhancement

#37 Configurable Kubernetes version setup
  .circleci/config.yml
  README.md
  cmd/cli/cmd.go
  docs/pupernetes_daemon.md
  docs/pupernetes_daemon_clean.md
  docs/pupernetes_daemon_run.md
  docs/pupernetes_daemon_setup.md
  environments/container-linux/ignition.yaml
  pkg/config/config.go
  pkg/job/systemd.go
  pkg/logging/logging.go
  pkg/options/clean_test.go
  pkg/options/options.go
  pkg/run/getter.go
  pkg/run/probe.go
  pkg/run/run.go
  pkg/run/state.go
  pkg/run/stop.go
  pkg/setup/clean.go
  pkg/setup/getter.go
  pkg/setup/manifests.go
  pkg/setup/secrets.go
  pkg/setup/setup.go
  pkg/setup/systemd.go
  pkg/setup/templates/1.10.go
  pkg/setup/templates/1.11.go
  pkg/setup/templates/1.5.go
  pkg/setup/templates/1.6.go
  pkg/setup/templates/1.7.go
  pkg/setup/templates/1.8.go
  pkg/setup/templates/1.9.go
  pkg/setup/templates/manifests.go
  pkg/setup/version.go
  pkg/setup/version_test.go
  pkg/util/random.go
  pkg/util/random_test.go
  pkg/util/systemd_action.go
Labels: enhancement

#43 New wait command
  cmd/cli/cmd.go
  docs/pupernetes.md
  docs/pupernetes_wait.md
  pkg/config/config.go
  pkg/wait/wait.go
Labels: enhancement

#44 Use a more portable version of listUnits
  pkg/job/systemd.go
  pkg/run/probe.go
  pkg/setup/manifests.go
  pkg/setup/systemd.go
  pkg/util/systemd_action.go
  pkg/wait/wait.go
Labels: bug

#47 Add notify to the systemd unit
  environments/container-linux/ignition.yaml
Labels: enhancement

#48 Command line daemon alias
  cmd/cli/cmd.go
Labels: enhancement

#49 Run over old systemd platform
  .ci/pupernetes-validation.sh
  .ci/pupernetes-validation.yaml
  .circleci/config.yml
  .travis.yml
  pkg/api/api.go
  pkg/job/systemd.go
  pkg/logging/logging.go
  pkg/run/probe.go
  pkg/run/run.go
  pkg/run/stop.go
  pkg/setup/templates/1.10.go
  pkg/setup/templates/1.11.go
  pkg/setup/templates/1.5.go
  pkg/setup/templates/1.6.go
  pkg/setup/templates/1.7.go
  pkg/setup/templates/1.8.go
  pkg/setup/templates/1.9.go
  pkg/util/systemd_action.go
  pkg/wait/wait.go
Labels: enhancement

#50 Add SaaS CI examples
  README.md
Labels: enhancement

#58 Fix the signal reset on SIGs during Stop
  pkg/run/run.go
  pkg/run/stop.go
  pkg/util/systemd_action.go
Labels: bug

#56 Introduce ineffassign, golint and misspell
  .circleci/config.yml
  Makefile
  cmd/cli/cmd.go
  docs/pupernetes_daemon_run.md
  pkg/api/client.go
  pkg/config/config.go
  pkg/job/systemd.go
  pkg/logging/logging.go
  pkg/options/clean.go
  pkg/options/drain.go
  pkg/options/options.go
  pkg/run/delete.go
  pkg/run/getter.go
  pkg/run/run.go
  pkg/run/state.go
  pkg/run/stop.go
  pkg/setup/clean.go
  pkg/setup/getter.go
  pkg/setup/setup.go
  pkg/setup/systemd.go
  pkg/setup/templates/manifests.go
  pkg/wait/wait.go
Labels: refactoring

#60 Use RSA standard library
  README.md
  pkg/setup/requirements.go
  pkg/setup/secrets.go
Labels: enhancement, refactoring

#59 Basic check on the memory
  Gopkg.lock
  LICENSE-3rdparty.csv
  README.md
  pkg/setup/requirements/requirements.go
  pkg/setup/setup.go
  vendor/github.com/cloudfoundry/gosigar/.gitignore
  vendor/github.com/cloudfoundry/gosigar/.travis.yml
  vendor/github.com/cloudfoundry/gosigar/Gopkg.lock
  vendor/github.com/cloudfoundry/gosigar/Gopkg.toml
  vendor/github.com/cloudfoundry/gosigar/LICENSE
  vendor/github.com/cloudfoundry/gosigar/NOTICE
  vendor/github.com/cloudfoundry/gosigar/README.md
  vendor/github.com/cloudfoundry/gosigar/Vagrantfile
  vendor/github.com/cloudfoundry/gosigar/concrete_sigar.go
  vendor/github.com/cloudfoundry/gosigar/sigar_darwin.go
  vendor/github.com/cloudfoundry/gosigar/sigar_format.go
  vendor/github.com/cloudfoundry/gosigar/sigar_interface.go
  vendor/github.com/cloudfoundry/gosigar/sigar_linux.go
  vendor/github.com/cloudfoundry/gosigar/sigar_shared.go
  vendor/github.com/cloudfoundry/gosigar/sigar_unix.go
  vendor/github.com/cloudfoundry/gosigar/sigar_util.go
  vendor/github.com/cloudfoundry/gosigar/sigar_windows.go
  vendor/github.com/cloudfoundry/gosigar/sys/windows/doc.go
  vendor/github.com/cloudfoundry/gosigar/sys/windows/ntquery.go
  vendor/github.com/cloudfoundry/gosigar/sys/windows/privileges.go
  vendor/github.com/cloudfoundry/gosigar/sys/windows/syscall_windows.go
  vendor/github.com/cloudfoundry/gosigar/sys/windows/version.go
  vendor/github.com/cloudfoundry/gosigar/sys/windows/zsyscall_windows.go
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: enhancement

#62 Add pprof
  pkg/api/api.go
Labels: enhancement

#64 Use a dedicated timeout for each package
  cmd/cli/cmd.go
  docs/pupernetes_daemon.md
  docs/pupernetes_daemon_clean.md
  docs/pupernetes_daemon_run.md
  docs/pupernetes_daemon_setup.md
  docs/pupernetes_reset.md
  docs/pupernetes_wait.md
  pkg/api/client.go
  pkg/config/config.go
  pkg/run/run.go
  pkg/setup/getter.go
Labels: bug, refactoring

#63 Update the readme
  README.md
  RELEASE.md
  docs/pupernetes.jpg
  environments/ubuntu/README.md
Labels: enhancement, refactoring

#69 Introduce sonobuoy in CI
  .ci/sonobuoy.sh
  .circleci/config.yml
  cmd/cli/cmd.go
  docs/pupernetes_daemon.md
  docs/pupernetes_daemon_clean.md
  docs/pupernetes_daemon_run.md
  docs/pupernetes_daemon_setup.md
  pkg/config/config.go
  pkg/setup/kubeclient.go
  pkg/setup/setup.go
  pkg/setup/systemd.go
Labels: enhancement

#74 Remove the archive on extract failure
  pkg/setup/binary.go
  pkg/setup/binary_cni.go
  pkg/setup/binary_etcd.go
  pkg/setup/binary_hyperkube.go
  pkg/setup/binary_vault.go
Labels: enhancement

#75 Remove the duplicated flag in manifests
  pkg/setup/templates/1.10.go
  pkg/setup/templates/1.11.go
  pkg/setup/templates/1.5.go
  pkg/setup/templates/1.6.go
  pkg/setup/templates/1.7.go
  pkg/setup/templates/1.8.go
  pkg/setup/templates/1.9.go
Labels: bug

#76 Stop the systemd units in a reverse order
  pkg/run/stop.go
  pkg/setup/clean.go
  pkg/setup/setup.go
Labels: bug

#77 Add hyperkube 1.11
  .travis.yml
Labels: enhancement
